name: Automate Processing
on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *' # Runs every hour

jobs:
  process:
    runs-on: ubuntu-latest
    env:
        SMARTSHEET_ACCESS_TOKEN: ${{ secrets.SMARTSHEET_ACCESS_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install pandas smartsheet-python-sdk

      - name: Set up Git user
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Set up Git with PAT
        run: |
         git remote set-url origin https://x-access-token:${{ secrets.MY_PERSONAL_ACCESS_TOKEN }}@github.com/TerondaDavis/DC-Circulator-Operations.git

      - name: Run Script
        run: python Main_Script.py

      - name: Commit and push
        run: |
          git add Data/*.csv
          git commit -m 'Update CSV files'
          git push
